version: '3.8'
services: 
  xivmarketboard_api:
    build: 
        context: .
        dockerfile: /XIVMarketBoard_Api/Dockerfile
    ports:
    - "8000:80"
    - "8001:443"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 