name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout 
      uses: actions/checkout@v2.4.2
      
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      with:
          context: ./
          file: ./XIVMarketBoard_Api/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/XIVMarketBoard_Api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/XIVMarketBoard_Api:buildcache,mode=max
